### ISSUE TITLE
Replace CRA with Vite

### ISSUE THREAD

**Issue by mbund** [ShannonMcKinney1/CSE-Course-Chart#1]
Create React App is not generally advisable especially for getting started with React. A more robust alternative would be [Vite](https://vitejs.dev/guide), and I suggest re-bootstrapping the project in its early stages to Vite while it is still easy. Additionally, moving over to TypeScript will allow for more maintainable code, with an easier developer experience. It is built in to most modern frameworks.

You can bootstrap a Vite app by following the guide linked above, essentially:
```
npm create vite@latest my-react-app
```
and selecting options for `React` and `TypeScript`

**Comment by ShannonMcKinney1** [comment]
Done :) thanks for the input!
